Console.WriteLine("Enter number a: ");
int a = int.Parse(Console.ReadLine());
Console.WriteLine("Enter number b: ");
int b = int.Parse(Console.ReadLine());
Console.WriteLine("Enter number c: ");
int c = int.Parse(Console.ReadLine());
int max = a;
if(a > max) max = a;
if(b > max) max = b;
if(c > max) max = c;
Console.Write("max = ");
Console.WriteLine(max);